require "aws-sdk"

require "aws-wrapper/version"
require "aws-wrapper/core"
require "aws-wrapper/ec2"
require "aws-wrapper/ec2/acl"
require "aws-wrapper/ec2/vpc"
require "aws-wrapper/ec2/subnet"
require "aws-wrapper/ec2/internet_gateway"
require "aws-wrapper/ec2/network_interface"
require "aws-wrapper/ec2/route_table"
require "aws-wrapper/ec2/security_group"
require "aws-wrapper/ec2/instance"
require "aws-wrapper/elb"
